#!/usr/bin/env bash

# Commented code to build only on main branch push
# Uncomment if you want to enable this feature

# main_branch="main"

# branch="$(git rev-parse --abbrev-ref HEAD)"

# if [ "$branch" = "$main_branch" ]; then
#   pnpm run build
# fi
# uncomment to test
# exit 1
pnpm run build
